# TODO: Use these strictly in development (extend from production config)

# JS Shell Docker Compose Development Configuration

version: '3.1'
services:
  # Creates a self-signed SSL proxy for local development
  # This permits access to media devices (e.g. microphone / camera) during development
  # 
  # This is not intended to run on a production web server
  #
  # TODO: Possibly bugfix; not able to use custom port / Docker network alias from dev_proxy
  dev_proxy:
    # build: https://github.com/zenOSmosis/docker-dev-ssl-proxy.git
    # TODO: Add depends on stt-socket
    build: ./docker_modules/dev-ssl-proxy
    # depends_on:
    #  - stt-socket
    network_mode: "host" # Using host network here so we can proxy to localhost addresses
    volumes:
      - ./docker_modules/dev-ssl-proxy:/app # Only during development
    environment:
      - PROXY_ADDRESS=http://127.0.0.1:3001 # Important, don't use quotations here, or it may break the template

  backend:
    build: ./backend
    volumes:
      # - ./backend:/shell/backend # Only during development
      - ./:/shell # Only during development
    environment:
      - NODE_ENV="development"
    links:
      - frontend
      - dev_proxy # During development
    command: ["npm", "run", "start"]
    ports:
      - 3001:3001

  # Note: No direct network access to frontend; proxied through backend
  frontend:
    build: ./frontend
    volumes:
      # Backend is mapped w/ frontend because of shared object in utils/bind
      # jh: Not yet sure how this will work in production environment
      # - ./frontend:/shell/frontend # Only during development
      # - ./backend:/shell/backend # Only during development
      # - ./cli:/shell/cli # Only during development
      - ./:/shell # Only during development
    environment:
      - NODE_ENV="development"
      # - HTTPS=true
    command: ["npm", "run", "start"]
    ports:
      - 3000:3000

  # Prototype STT socket w/ Socket.io interface
  stt-socket:
    build: ./docker_modules/stt-socket
    volumes:
      - ./docker_modules/stt-socket:/app # Only during development
      - /tmp/stt-socket:/tmp # Only during development
    ports:
      - 8888:8888